### ISSUE TITLE
Google Play’s 16 KB page size compatibility requirement

### ISSUE THREAD

**Issue by Lukitaduarte** [DataDog/dd-sdk-flutter#834]
### Question

Apparently your Flutter SDK isn't ready for this change, and the deadline is November 1st. Is this on the radar for a future release? I tested with the latest version (datadog_flutter_plugin: ^2.13.1).

https://android-developers.googleblog.com/2025/05/prepare-play-apps-for-devices-with-16kb-page-size.html

<img width="1245" height="25" alt="Image" src="https://github.com/user-attachments/assets/165509e8-a5a0-489f-9114-a341c2134e02" />

**Comment by fuzzybinary** [comment]
We've been getting this question a lot (see #804) but this should have been fixed with dd-android-sdk 2.20.0 (see https://github.com/DataDog/dd-sdk-android/pull/2580) which was included in datadog_flutter_plugin 2.11.0+.

It appears that the only change needed for this to work is to upgrade the version of NDK. Is it possible you have a version set in your build.gradle that is below the expected version for 16 KB page sizes?

**Comment by franco-conroo** [comment]
Seems like `compileSdkVersion 34` also needs to be updated as well. Since we have following exception trying to build our app with upgraded Android Requirements:

` What went wrong:
Execution failed for task ':datadog_flutter_plugin:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:

       1.  Dependency 'androidx.metrics:metrics-performance:1.0.0-beta02' requires libraries and applications that
           depend on it to compile against version 35 or later of the
           Android APIs.

           :datadog_flutter_plugin is currently compiled against android-34.

           Recommended action: Update this project to use a newer compileSdk
           of at least 35, for example 36.`

**Comment by fuzzybinary** [comment]
Yes, sorry this was known. I should have added it to release notes as a potential breaking change.

Did this solve your issue?

**Comment by franco-conroo** [comment]
No worries! 
We still get the issue with dd-sdk version `2.13.1` though 🤔
Our NDK version is the latest stable (ndkVersion "28.2.13676358") so I think the compileSdkVersion of the dd-sdk should be updated?

**Comment by samirsimnica** [comment]
[https://github.com/DataDog/dd-sdk-flutter/pull/835](https://github.com/DataDog/dd-sdk-flutter/pull/835)
This PR should fix the mentioned issue, tried building it myself and it succeed.

**Comment by fuzzybinary** [comment]
Interesting, I'm very curious why I didn't get hit with an issue with `compileSdkVersion` in my testing of the release....

But it definitely should be updated. I'll try to get it in and issue a patch release to 2.13 out ASAP.

**Comment by fuzzybinary** [comment]
`datadog_flutter_plugin 2.13.2` with the updated `compileSdk` is now out on pub. @samirsimnica, @franco-conroo, @Lukitaduarte can you see if this fixes your issue?

**Comment by franco-conroo** [comment]
Thanks for the quick response, issue seems to be fixed!

**Comment by samirsimnica** [comment]
Can also confirm that it's fixed, thank you!

**Comment by Lukitaduarte** [comment]
It worked perfectly! Thank you @fuzzybinary 🚀 

<img width="1004" height="23" alt="Image" src="https://github.com/user-attachments/assets/e64013db-3f97-40e0-ae0d-674b9f012190" />
